data:
  races:
    - Chihuahua
    - German_shepherd
    - golden_retriever
    - Siberian_husky
    - pug
    - Rottweiler
    - French_bulldog
    - Old_English_sheepdog
    - Doberman
    - standard_poodle
